import pandas as pd
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi


# Options:
#######################################
collection_name = "search_page_data"
query_filter = {
    'keyword': 'pants',
    'price': {'$gt': 20},
    'rating': {'$gt': 4.5}
    }
#######################################


extract_options = {
    # '_id': 1, # This is automatically generated by MongoDB, usually useless.
    "ASIN": 1, # This is the primary key.
    "title": 1,
    "price": 1,
    "rating": 1,
    "image": 1,
    "description": 1,
    "reviews": 1,
    "search_url": 1,
    "product_url": 1,
    "category": 1,
    "keyword": 1
}

db_url = "mongodb+srv://tzb:123qweasdzxc@cluster0.ly0rn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
client = MongoClient(db_url, server_api=ServerApi('1'))
db = client["449project"]
col = db[collection_name]

documents = col.find(query_filter, extract_options)

extracted_data = []
for doc in documents:
    extracted_element = {
        # "_id": str(doc.get('_id')),
        "ASIN": doc.get('ASIN'),
        "category": doc.get('category'),
        "image": doc.get('image'),
        "price": doc.get('price'),
        "rating": doc.get('rating'),
        "title": doc.get('title'),
        "description": doc.get('description'),
        "reviews": doc.get('reviews'),
        "search_url": doc.get('search_url'),
        "product_url": doc.get('product_url')
    }
    extracted_data.append(extracted_element)

df = pd.DataFrame(extracted_data)
df.to_csv("amazon_data_extract_results.csv", index=False)

print(f"Number of data extracted: {len(extracted_data)}")
